GET https://cse-341-project1-0a7o.onrender.com/contacts

###
GET https://cse-341-project1-0a7o.onrender.com/contacts/6822916447e0754a0f8e896b

###
PUT https://cse-341-project1-0a7o.onrender.com/contacts/
content-type: application/json

{
  "firstName": "Luisito",
  "lastName": "TortaPatel",
  "email": "luisito@example.com",
  "favoriteColor": "red",
  "birthday": "1991-07-07"
}

###
POST https://cse-341-project1-0a7o.onrender.com/contacts/
content-type: application/json

{
  "firstName": "Manguito",
  "lastName": "Melon",
  "email": "manguito@example.com",
  "favoriteColor": "verde",
  "birthday": "1891-07-06"
}

###
DELETE https://cse-341-project1-0a7o.onrender.com/contacts/6827ed8e4ea6805258f454c1